import {test,expect} from '@playwright/test';
const uid='11111111-1111-4111-8111-111111111111';
const project='https://rhlkwuxpqvfgfuguzkfm.supabase.co';
async function backend(page,{admin=false,failSearch=false,offline=false}={}){
 const writes=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://fonts.googleapis.com/**',r=>r.fulfill({body:'',contentType:'text/css'}));await page.route('https://fonts.gstatic.com/**',r=>r.abort());
 if(admin)await page.addInitScript(({uid})=>{const b=x=>btoa(JSON.stringify(x)).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');const token=b({alg:'HS256',typ:'JWT'})+'.'+b({sub:uid,role:'authenticated',exp:Math.floor(Date.now()/1000)+7200})+'.testsignature';localStorage.setItem('sb-rhlkwuxpqvfgfuguzkfm-auth-token',JSON.stringify({access_token:token,refresh_token:'mock-refresh-only',expires_in:7200,expires_at:Math.floor(Date.now()/1000)+7200,token_type:'bearer',user:{id:uid,email:'qa@example.invalid',role:'authenticated',app_metadata:{provider:'email'},user_metadata:{display_name:'QA'},aud:'authenticated',created_at:new Date().toISOString()}}));},{uid});
 await page.route(project+'/**',async route=>{
  const req=route.request(),url=new URL(req.url()),method=req.method();
  if(offline)return route.abort();
  const headers={'access-control-allow-origin':'*','content-type':'application/json','content-range':'0-0/0'};
  if(method==='OPTIONS')return route.fulfill({status:204,headers:{...headers,'access-control-allow-headers':'*','access-control-allow-methods':'*'}});
  if(method!=='GET'&&method!=='HEAD')writes.push({path:url.pathname,body:req.postDataJSON()});
  let body=[];
  if(url.pathname.endsWith('/search_help_center')){if(failSearch)return route.fulfill({status:503,headers,body:'{"message":"mock offline"}'});body=[{kind:'forum',title:'<img src=x onerror="window.injected=true">',description:'Résultat de sécurité',href:'forum-topic.html?id=00000000-0000-4000-8000-000000000000',category:'Communauté',score:999}];}
  else if(url.pathname.endsWith('/profiles'))body={id:uid,display_name:'QA',username:'qa',role:admin?'admin':'member',is_banned:false};
  else if(url.pathname.endsWith('/help_center_metrics'))body={since:'2026-09-01T00:00:00Z',usage:{views:0,searches:0,zero_results:0},feedback:{total:0,helpful:0,negative:0},support:{created:0,active:0,awaiting_user:0,first_response_hours:null,resolution_hours:null,satisfaction:null},queries:[],review_due:0,community:{topics:0,unanswered:0,resolved:0}};
  else if(url.pathname.endsWith('/knowledge_documents')){body=method==='POST'?null:[];}
  else if(url.pathname.endsWith('/service_components'))body=[{id:'22222222-2222-4222-8222-222222222222',slug:'workspace',name:'Squared Workspace',product:'Squared Workspace',enabled:true,public:true,lifecycle:'live',aggregate_status:true,current_status:'operational',monitor_type:'http',last_checked_at:'2025-01-01T00:00:00Z',description:'Mesure ancienne de test',response_ms:120}];
  else if(url.pathname.endsWith('/auth/v1/user'))body={id:uid,email:'qa@example.invalid'};
  else if(url.pathname.includes('/auth/'))body={};
  return route.fulfill({status:method==='POST'&&!url.pathname.includes('/rpc/')?201:200,headers,body:JSON.stringify(body)});
 });
 return {writes,errors};
}
test('navigation exclusif + logo conservé',async({page})=>{const {errors}=await backend(page);await page.goto('/');await expect(page.locator('.hc-brand-logo')).toBeVisible();const toggles=page.locator('.hc-sub-toggle');await expect(toggles.first()).toBeVisible();await toggles.nth(0).click();await expect(page.locator('.hc-item.child-open')).toHaveCount(1);await toggles.nth(1).click();await expect(page.locator('.hc-item.child-open')).toHaveCount(1);await expect(toggles.nth(1)).toHaveAttribute('aria-expanded','true');await expect(toggles.nth(0)).toHaveAttribute('aria-expanded','false');await page.screenshot({path:'test-results/home-desktop.png',fullPage:true});expect(errors).toEqual([]);});
test('recherche texte complet de secours',async({page})=>{const {errors}=await backend(page,{failSearch:true});await page.goto('/search.html');await page.locator('#unifiedQuery').fill('invitation');await page.locator('#unifiedSearch button[type=submit]').click();await expect(page.locator('#unifiedResults')).toContainText('Activer son accès');await expect(page.locator('#searchState')).toContainText('locale');expect(errors).toEqual([]);});
test('aucune injection HTML depuis un résultat du forum',async({page})=>{const {errors}=await backend(page);await page.goto('/search.html');await page.locator('#unifiedQuery').fill('test');await page.locator('#unifiedSearch button[type=submit]').click();await expect(page.locator('#unifiedResults')).toContainText('<img');await expect(page.locator('#unifiedResults img')).toHaveCount(0);expect(await page.evaluate(()=>window.injected)).toBeUndefined();expect(errors).toEqual([]);});
test('palette globale échappe aussi les résultats',async({page})=>{const {errors}=await backend(page);await page.goto('/');await page.waitForFunction(()=>!!window.SQSearchBackend);await page.locator('#searchTrigger').click();await page.locator('#searchInput').fill('test');await expect(page.locator('#searchResults')).toContainText('<img');await expect(page.locator('#searchResults img')).toHaveCount(0);await page.keyboard.press('Escape');await expect(page.locator('#searchModal')).not.toHaveClass(/open/);expect(errors).toEqual([]);});
test('statut ancien jamais transformé en opérationnel',async({page})=>{const {errors}=await backend(page);await page.goto('/server-status.html');await expect(page.locator('#opsStatusSnapshot')).toContainText('Mesure ancienne');await expect(page.locator('#opsStatusSnapshot [data-state=operational]')).toHaveCount(0);expect(errors).toEqual([]);});
test('admin visiteur redirigé sans afficher de données',async({page})=>{const {errors}=await backend(page);await page.goto('/admin.html');await page.waitForURL(/login\.html/);await expect(page.locator('#opsPanel')).toHaveCount(0);expect(errors).toEqual([]);});
test('admin simulé : métriques honnêtes et création de brouillon',async({page})=>{const {errors,writes}=await backend(page,{admin:true});await page.goto('/admin.html');await expect(page.locator('[data-ops-tab=knowledge]')).toBeVisible();await page.locator('[data-ops-tab=analytics]').click();await expect(page.locator('#opsPanel')).toContainText('Non mesuré');await expect(page.locator('#opsPanel')).not.toContainText('100 %');await page.locator('[data-ops-tab=knowledge]').click();await page.locator('[data-doc-new]').click();await expect(page.locator('dialog')).toBeVisible();await page.locator('dialog [name=title]').fill('Guide de test non publié');await page.locator('dialog [name=description]').fill('Test du workflow de brouillon');await page.locator('dialog [name=content]').fill('## Objectif\nDocument de test simulé, jamais envoyé à la production.');await page.locator('dialog button[type=submit]').click();await expect(page.locator('#opsNotice')).toContainText('enregistré');expect(writes.some(x=>x.path.endsWith('/knowledge_documents')&&x.body.status==='draft')).toBe(true);expect(errors).toEqual([]);});
test('mobile : page de statut et recherche sans débordement',async({page})=>{const {errors}=await backend(page);await page.setViewportSize({width:390,height:844});await page.goto('/server-status.html');await expect(page.locator('#opsStatusSnapshot')).toContainText('Mesure ancienne');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'test-results/status-mobile.png',fullPage:true});await page.goto('/search.html');await page.locator('#unifiedQuery').fill('invitation');await page.locator('#unifiedSearch button[type=submit]').click();await expect(page.locator('#unifiedResults')).toContainText('invitation');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(errors).toEqual([]);});
test('panne de service : message explicite sans chargement infini',async({page})=>{const {errors}=await backend(page,{offline:true});await page.goto('/server-status.html');await expect(page.locator('#opsStatusSnapshot')).toContainText('Chargement impossible');await expect(page.locator('#opsStatusSnapshot [data-retry]')).toBeVisible();expect(errors).toEqual([]);});
