"""Versioned public guides. UI claims reference a pinned Workspace web source.
Native distribution is described conditionally, never assumed to be live.
"""
import json,re,html,os
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def read(p):return (ROOT/p).read_text()
def write(p,s):
    f=ROOT/p;f.parent.mkdir(parents=True,exist_ok=True);f.write_text(s)
def section(id,title,body):return f'<section class="doc-block" id="{id}"><h2>{title}</h2>{body}</section>'
portal='https://workspace.app.squaredgroup.studio/'
source='https://github.com/squaredgroup/squared-workspace-web/blob/c355aa6eaa3a3b4ad0d5da5bc47b50e1354fe852/'
provenance='<p class="sq-guide-provenance">Procédure vérifiée sur le code du portail web Squared Workspace du 18 septembre 2026. Les captures montrent les formulaires réels sans données personnelles. Elles ne prouvent pas la disponibilité actuelle du serveur et ne représentent pas l’interface de l’application native. <a href="'+source+'js/modules/auth.js" target="_blank" rel="noreferrer">Source de la procédure web</a>.</p>'
def figure(name,alt):return '<figure class="sq-guide-capture"><img loading="lazy" src="../assets/guides/'+name+'.png" alt="'+alt+'"><figcaption>Portail web Workspace : '+alt+'. Formulaire réel, aucune donnée personnelle saisie.</figcaption></figure>'

def make_page(path,title,desc,body,article=True):
    template=read('asking-for-help.html')
    template=re.sub(r'<title>.*?</title>',f'<title>{html.escape(title)} — Squared Help Center</title>',template,flags=re.S)
    template=re.sub(r'<meta name="description" content="[^"]*">','<meta name="description" content="'+html.escape(desc,quote=True)+'">',template)
    template=re.sub(r'(<div class="crumbs">.*?<strong>).*?(</strong>)',lambda m:m[1]+html.escape(title)+m[2],template,count=1,flags=re.S)
    header='<header class="article-head"><div class="eyebrow">Squared · Aide pratique</div><h1>'+html.escape(title)+'</h1><p>'+html.escape(desc)+'</p><div class="article-meta"><span class="pill">Guide pratique</span><span class="pill">Révisé le 19 septembre 2026</span></div></header>'
    if article:
        template=re.sub(r'<article class="article">.*?</article>',lambda m:'<article class="article">'+header+body+'</article>',template,flags=re.S)
    else:
        template=re.sub(r'<div class="article-layout">.*?<aside class="aside-toc".*?</aside>\s*</div>',lambda m:header+body,template,flags=re.S)
    if '/' in path:
        template=re.sub(r'(href|src)="(?!https?:|#|mailto:|\.\./)([^"?]+)',lambda m:m[1]+'="../'+m[2],template)
    write(path,template)

activation=section('avant','Avant de commencer','''<p>Ce guide s’adresse à une personne invitée dans un espace client ou collaborateur. Ayez l’invitation, l’adresse e-mail destinataire et votre code d’invitation à portée de main. Le compte du centre d’aide est distinct : créer un compte ici ne crée pas un accès Workspace.</p><p>Vous avez déjà activé votre accès ? Passez à <a href="workspace/workspace-login.html">Me connecter à Workspace</a> au lieu d’activer un deuxième compte.</p>''')+section('etapes','Activer votre accès',f'''<ol><li>Ouvrez le lien de l’invitation ou le <a href="{portal}">portail web Workspace</a>. Sur la page Connexion, choisissez <strong>Activer un accès</strong>.</li><li>Renseignez <strong>Prénom</strong>, <strong>Nom</strong> et l’<strong>Adresse e-mail</strong> qui a reçu l’invitation. Une autre adresse peut ne pas correspondre à l’accès prévu.</li><li>Copiez votre <strong>Code d’invitation</strong> dans le champ dédié. N’envoyez jamais ce code dans le forum ou un ticket.</li><li>Choisissez votre <strong>Mot de passe</strong>. Dans cette version du portail web, il faut au moins 10 caractères, une majuscule, une minuscule et un chiffre.</li><li>Lisez les conditions présentées, cochez l’acceptation si vous les acceptez, puis sélectionnez <strong>Activer mon espace</strong> une seule fois.</li></ol>'''+figure('workspace-activation','Les champs du formulaire « Activer votre accès »'))+section('resultat','Le résultat attendu','''<p>Lorsque le serveur accepte l’activation, le portail poursuit l’ouverture de votre espace. Vérifiez que vous retrouvez le contexte attendu. Un message d’erreur ou une attente sans fin ne constitue pas une confirmation d’activation.</p><p>Les rubriques visibles dépendent de vos autorisations. L’absence de certains outils internes n’implique pas une activation incomplète.</p>''')+section('problemes','Invitation absente, refusée ou expirée','''<p>Vérifiez les courriers indésirables et l’adresse destinataire. Si l’invitation manque ou n’est plus valide, demandez à votre interlocuteur Squared de vérifier l’accès et de renvoyer une invitation. N’inventez pas de code et ne multipliez pas les créations de comptes.</p><p>En cas d’erreur réseau, revenez à Connexion et utilisez <strong>Vérifier la connexion au serveur</strong>. Le succès de l’installation ou du chargement de la page n’est pas une preuve de fonctionnement de l’API.</p>''')+section('suite','Vous êtes encore bloqué ?','''<p>Notez la date, le type d’appareil, le message exact et l’étape atteinte. Masquez le code d’invitation et l’adresse complète avant toute capture publique.</p><a class="btn" href="diagnostic.html?product=workspace&amp;issue=access">Me guider pour mon accès</a>''')+provenance
make_page('workspace/workspace-activation.html','Activer mon espace Workspace','La procédure d’invitation du portail web, étape par étape, sans créer de compte en double.',activation)

login=section('choisir','Vérifier le bon compte',f'''<p>Ouvrez le <a href="{portal}">portail web Workspace</a>. Son écran Connexion n’est pas celui du centre d’aide. Une inscription au forum ne donne pas automatiquement accès à un projet client ou à l’équipe.</p><p>Premier accès ? Commencez par <a href="workspace/workspace-activation.html">activer l’invitation</a>. Compte déjà activé ? Utilisez les étapes suivantes.</p>''')+section('connexion','Me connecter', '''<ol><li>Dans <strong>Adresse e-mail</strong>, saisissez l’adresse liée à votre espace.</li><li>Renseignez votre <strong>Mot de passe</strong>, puis sélectionnez <strong>Se connecter</strong>.</li><li>Si <strong>Vérification renforcée</strong> apparaît, utilisez votre passkey ou l’un de vos codes de récupération, selon les options réellement proposées.</li><li>Après ouverture, contrôlez le contexte et les rubriques accessibles. N’utilisez pas le compte d’une autre personne pour retrouver une donnée.</li></ol>'''+figure('workspace-login','Connexion avec Adresse e-mail, Mot de passe et liens de récupération'))+section('recuperer','Mot de passe oublié','''<p>Sur Connexion, choisissez <strong>Mot de passe oublié</strong>, entrez votre adresse et sélectionnez <strong>Envoyer le lien</strong>. Le portail affiche un message neutre, même si le compte n’existe pas : ce message n’est pas une confirmation de l’existence du compte.</p><p>Ouvrez le lien reçu. Si le portail propose <strong>Saisir un code reçu</strong>, utilisez le code de réinitialisation dans ce formulaire, puis le nouveau mot de passe. Ne partagez ni ce lien ni ce code.</p><p>Après une mise à jour réussie, revenez à Connexion et utilisez le nouveau mot de passe. Une demande de réinitialisation ne crée pas un espace et ne remplace pas une invitation.</p>''')+section('erreurs','Passkey et erreurs de réseau','''<p>Une passkey dépend de l’appareil et du domaine sur lequel elle est utilisable. Si elle est refusée sur le portail web, utilisez seulement les alternatives prévues : mot de passe et, si demandé, code de récupération. Ne désactivez pas un contrôle de sécurité pour contourner l’erreur.</p><p>Le lien <strong>Vérifier la connexion au serveur</strong> aide à distinguer une erreur de réseau d’une erreur d’identifiants. Si le navigateur bloque l’accès à l’API, répéter les mots de passe ne corrige pas la configuration du serveur. Signalez le message exact, pas vos codes.</p>''')+section('suite','Besoin d’une autre voie ?','''<p>Vous n’avez plus accès à votre messagerie ou aucun moyen de seconde vérification ? Utilisez le <a href="access-help.html">parcours de récupération d’accès</a>. Une vérification par l’équipe peut être nécessaire ; ce guide ne permet pas de contourner l’identité.</p>''')+provenance
make_page('workspace/workspace-login.html','Me connecter à Workspace','Distinguer compte Workspace et Help Center, récupérer son accès et comprendre une erreur de connexion.',login)

docs=section('contexte','Avant de modifier quoi que ce soit','''<p>Ce guide concerne un document ou un livrable que vous attendiez dans Workspace. Vous devez disposer d’un accès au bon espace et au projet concerné. Ne recréez pas un fichier pour résoudre un problème de visibilité : vous risqueriez d’introduire un doublon.</p><p>Les documents de votre projet ne sont pas les guides publics de ce centre d’aide. Un favori du forum n’est pas un fichier client.</p>''')+section('verifications','Les vérifications à effectuer','''<ol><li>Vérifiez que vous utilisez le compte et le contexte associés au projet. Le titre ou le nom de votre interlocuteur peut aider à confirmer le bon espace.</li><li>Consultez <strong>Documents</strong>, puis <strong>Livrables</strong>. Un document de travail et un résultat remis pour validation peuvent être rangés dans des rubriques différentes.</li><li>Effacez la recherche du module pour revenir à la liste disponible. Dans le portail web, la recherche filtre les titres et les statuts.</li><li>Vérifiez le titre et la version attendus avec l’équipe. Un fichier renommé peut ne plus correspondre au mot recherché.</li><li>Si l’élément reste absent, demandez au responsable du projet de vérifier son rattachement et vos droits. Un écran vide ne permet pas, à lui seul, de conclure que le fichier a été supprimé.</li></ol>''')+section('attention','Ce qu’il ne faut pas faire','''<p>Dans la version web examinée, le bouton <strong>Fichier</strong> ouvre un sélecteur de fichier pour ajouter un fichier. Ce n’est pas un bouton de téléchargement. Ne l’utilisez pas pour « ouvrir » un document existant.</p><p>Ne choisissez pas <strong>Archiver</strong>, <strong>Modifier</strong> ou <strong>Nouveau</strong> pour corriger une donnée absente. Si aucune action de consultation attendue n’est disponible dans votre version, demandez à l’équipe le bon accès de remise du livrable.</p>''')+section('resultat','Le résultat attendu','''<p>Vous identifiez l’élément attendu avec le bon titre et la bonne version, ou le responsable confirme quel accès manque. Le simple fait de voir une rubrique n’atteste pas l’accès à tous les fichiers du groupe.</p><p>Avant de contacter le support, préparez le produit, la rubrique, le projet concerné et le message observé. Dans une demande privée, partagez seulement le minimum nécessaire. Ne publiez pas le contrat, le fichier client complet ou une URL d’accès privée dans le forum.</p><a class="btn" href="diagnostic.html?product=workspace&amp;issue=documents">Retrouver mon document : dépannage guidé</a>''')+'<p class="sq-guide-provenance">Basé sur le module de données du portail web : recherche par titre/statut, rubriques et action d’ajout de fichier. <a href="'+source+'js/modules/data.js" target="_blank" rel="noreferrer">Source vérifiée</a>. Ce guide ne suppose aucune fonction de téléchargement native non vérifiée.</p>'
make_page('workspace/workspace-documents.html','Je ne vois pas un document ou un livrable','Vérifier le contexte, la rubrique et le partage sans recréer ni écraser un fichier.',docs)

installation=section('choix','Choisir web ou application native',f'''<p>Le <a href="{portal}">portail web Workspace</a> s’ouvre dans un navigateur. Aucune installation de l’application native n’est nécessaire pour essayer cet accès. Le portail web et les apps natives peuvent proposer des interfaces ou des fonctions différentes.</p><p>Une bêta native nécessite une invitation et une version disponible pour votre appareil. Cette page ne promet pas qu’une distribution App Store, TestFlight ou un installateur Mac est actuellement public.</p>''')+section('beta','Installer une bêta reçue par invitation','''<ol><li>Ouvrez l’invitation officielle Squared sur l’appareil qui doit recevoir l’application. Ne récupérez pas un installateur depuis une discussion publique ou un site tiers.</li><li>Si l’invitation utilise <strong>TestFlight</strong>, installez l’application TestFlight fournie par Apple pour l’appareil concerné.</li><li>Ouvrez l’invitation, acceptez-la puis sélectionnez l’installation de la version proposée.</li><li>Ouvrez Workspace et utilisez votre accès Workspace. L’installation ne remplace pas l’activation d’un espace.</li></ol><p>Pour les étapes exactes et les versions compatibles, suivez les indications de <a href="https://testflight.apple.com/" target="_blank" rel="noreferrer">TestFlight d’Apple</a> et celles de votre invitation. Un compte du Help Center ne vous inscrit pas automatiquement à une bêta.</p>''')+section('mise-a-jour','Mettre à jour ou comprendre une expiration','''<p>Consultez la fiche de l’app dans TestFlight et utilisez la mise à jour lorsqu’une nouvelle build est proposée. Une build TestFlight est disponible au plus 90 jours ; après expiration, une nouvelle build doit être fournie par l’équipe. Réinstaller la même build expirée ne prolonge pas sa durée.</p><p>Avant une réinstallation, vérifiez avec l’équipe le traitement des données locales non synchronisées. Ce guide ne garantit pas qu’elles seront conservées.</p>''')+section('raccourci','Ajouter un raccourci web sur iPhone','''<p>Dans Safari, ouvrez le portail officiel puis le menu de partage. Le guide Apple décrit l’ajout <strong>Sur l’écran d’accueil</strong> et l’option d’ouverture comme app web lorsqu’elle est proposée. Cela crée un accès web ; cela ne transforme pas le portail en application native distribuée sur l’App Store.</p><p><a href="https://support.apple.com/fr-afri/guide/iphone/iphea86e5236/ios" target="_blank" rel="noreferrer">Guide Apple : ajouter une app web sur l’iPhone</a>.</p>''')+section('problemes','Lorsque l’installation échoue','''<p>Notez l’appareil, la version du système, le canal utilisé et le message affiché. Une invitation invalide, une build expirée et un mot de passe refusé sont trois problèmes différents. Utilisez le diagnostic pour préparer une demande cohérente sans transmettre l’invitation privée.</p><a class="btn" href="diagnostic.html?product=workspace&amp;issue=installation">Vérifier mon installation</a>''')
make_page('workspace/workspace-installation.html','Installer ou ouvrir Workspace','Choisir le portail web ou une bêta native, installer une version disponible et garder ses accès distincts.',installation)

roles=section('principe','Comprendre ce qui est visible','''<p>Les rubriques et actions de Workspace dépendent du rôle et des autorisations de votre compte. Le portail web filtre sa navigation en fonction des sections accessibles. Le rôle choisi dans un parcours d’aide n’accorde aucun droit : les données restent contrôlées par le serveur.</p><p>Un client n’a pas besoin de voir l’administration de toute l’entreprise. Un collaborateur peut disposer de missions sans être autorisé à modifier les droits d’accès.</p>''')+section('rubrique','Une rubrique ou un élément manque','''<ol><li>Confirmez que vous êtes connecté au compte qui a reçu l’accès.</li><li>Vérifiez avec votre interlocuteur le projet et les informations que cet accès doit couvrir.</li><li>Si la rubrique existe mais reste vide, effacez sa recherche et vérifiez le titre de l’élément.</li><li>Si une autorisation manque, demandez une vérification à l’équipe. Ne tentez pas de remplacer un identifiant dans l’URL ou de partager un compte pour voir le contenu.</li></ol>''')+section('demande','Demander le bon accès','''<p>Expliquez ce que vous devez faire, sur quel projet et jusqu’à quand. Ne demandez pas un rôle administrateur par défaut lorsqu’un simple accès au document suffit.</p><p>L’équipe habilitée doit vérifier l’identité, la responsabilité et le périmètre avant un changement. Si vous quittez un projet, signalez les accès qui ne sont plus nécessaires.</p>''')+section('resultat','Ce que vous devez obtenir','''<p>Une confirmation claire du périmètre autorisé, puis l’accès aux seules ressources nécessaires. Le guide d’aide ne peut pas attribuer lui-même un rôle.</p><a class="btn" href="workspace/workspace-documents.html">Vérifier un document absent</a> <a class="btn" href="support.html">Demander une vérification privée</a>''')+'<p class="sq-guide-provenance">Navigation vérifiée dans le <a href="'+source+'js/app.js" target="_blank" rel="noreferrer">code du portail web</a>. Les permissions et données du serveur ne sont pas modifiées par ce centre d’aide.</p>'
make_page('workspace/workspace-roles.html','Comprendre mes rôles et mes accès','Distinguer une rubrique absente, une donnée filtrée et un besoin d’autorisation.',roles)

trouble=section('avant','Identifier le type de problème','''<p>Commencez par identifier le produit, l’appareil et l’action précise. Le chargement de la page web, l’ouverture d’une session et l’accès à une donnée sont des contrôles différents.</p><p>Le diagnostic propose trois parcours courts : accès, documents, installation. Il ne réinitialise aucun compte et n’envoie aucune demande à votre place.</p><a class="btn green" href="diagnostic.html?product=workspace">Démarrer le dépannage guidé</a>''')+section('reseau','Page chargée, mais connexion impossible','''<p>Sur la page Connexion du portail web, utilisez <strong>Vérifier la connexion au serveur</strong>. Notez le message. Un problème de communication entre le navigateur et l’API peut nécessiter une correction serveur ; il ne prouve pas que votre mot de passe est erroné.</p><p>N’ignorez jamais un avertissement de certificat et ne désactivez pas les protections du navigateur pour contourner le problème. Consultez les <a href="status.html">incidents déclarés</a> et distinguez « aucune mesure » de « service vérifié ».</p>''')+section('donnees','Une donnée n’apparaît pas','''<p>Vérifiez d’abord votre compte, la rubrique et la recherche. Ne recréez pas la donnée avant confirmation de sa source et de son partage. Suivez <a href="workspace/workspace-documents.html">Je ne vois pas un document</a>.</p>''')+section('preuve','Préparer une demande exploitable','''<p>Conservez l’heure approximative, la version de l’app ou du navigateur, la rubrique, l’action effectuée et le résultat attendu. Une capture doit masquer mots de passe, codes, liens d’invitation et contenus privés non nécessaires.</p><p>Le diagnostic peut préparer ces catégories dans le support ; vous relisez et complétez avant de soumettre. Le compte du support reste distinct de celui de Workspace.</p>''')+provenance
make_page('workspace/workspace-troubleshooting.html','Résoudre un problème Workspace','Un diagnostic concret avant de modifier un compte, un document ou une installation.',trouble)

make_page('parcours.html','Votre point de départ','Trois parcours pour trouver le bon guide sans connaître toute l’organisation de Squared.','<div id="journeyMount"></div><noscript><p>Choisissez un guide : <a href="workspace/workspace-activation.html">Activation</a>, <a href="workspace/workspace-installation.html">Installation</a> ou <a href="workspace/workspace-projects.html">Travail</a>.</p></noscript>',False)
make_page('diagnostic.html','Dépannage guidé','Trois questions, des vérifications concrètes et une demande préparée seulement si vous en avez besoin.','<div id="diagnosticMount"></div><noscript><p>JavaScript est nécessaire au diagnostic interactif. Vous pouvez lire les <a href="workspace/workspace-troubleshooting.html">vérifications Workspace</a> ou le <a href="access-help.html">guide de récupération</a>.</p></noscript>',False)
access=section('produit','De quel accès s’agit-il ?','''<p><strong>Centre d’aide :</strong> le compte permet de participer au forum et de suivre ses tickets. <strong>Workspace :</strong> l’accès aux projets suit une invitation distincte. Réinitialiser le compte de l’un ne réinitialise pas automatiquement l’autre.</p><a class="btn" href="forgot-password.html">Mot de passe du centre d’aide</a> <a class="btn" href="workspace/workspace-login.html">Connexion à Workspace</a>''')+section('email','J’ai encore accès à ma messagerie','''<p>Utilisez la récupération du produit concerné. Consultez vos courriers indésirables et utilisez un lien récent. Le lien et les codes doivent rester privés. Une erreur de réseau persistante se signale avec son message exact plutôt qu’en multipliant les demandes de mot de passe.</p>''')+section('sans-email','Je ne peux pas utiliser la récupération','''<p>Si votre messagerie est inaccessible ou que la récupération ne suffit pas, contactez votre interlocuteur Squared habituel ou le <a href="https://www.squaredgroup.studio/contact" target="_blank" rel="noreferrer">point de contact officiel</a>. Indiquez seulement le produit et la nature du blocage, puis attendez les instructions de vérification.</p><p>Ne transmettez jamais mot de passe, passkey, code de récupération, pièce d’identité ou document client sans procédure explicitement définie avec l’équipe. Ce parcours ne contourne aucune vérification d’identité et n’expose pas les tickets d’un compte déconnecté.</p>''')+section('incident','Je suspecte un incident','''<p>Consultez le <a href="status.html">statut des services</a> sans avoir à vous connecter. Une mesure absente ou ancienne n’est pas une preuve de bon fonctionnement. Le <a href="diagnostic.html">dépannage guidé</a> peut vous aider à décrire les vérifications déjà effectuées.</p>''')
make_page('access-help.html','Je n’arrive pas à me connecter','Récupérer le bon accès ou contacter Squared sans devoir d’abord ouvrir un ticket connecté.',access)

# Preserve reviewed member sources and journeys after legacy access-page generation.
if (ROOT / "scripts/editorial/build.py").exists():
    import runpy
    runpy.run_path(str(ROOT / "scripts/editorial/build.py"), run_name="__main__")
